Next try to fix clang-tidy CI

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -9,7 +9,11 @@ on:
 jobs:
   clang-tidy:
     name: Clang-Tidy
-    runs-on: ubuntu-latest
+
+    runs-on: ubuntu-20.04
+    env:
+      CC: clang
+      CXX: clang++
 
     steps:
     - name: Checkout
@@ -27,6 +31,7 @@ jobs:
           libsdl2-dev \
           libsdl2-ttf-dev \
           zlib1g-dev \
+          python-yaml \
           clang-tidy \
           # EOF
         echo "::endgroup::"
@@ -35,15 +40,19 @@ jobs:
 
     - name: Check
       run: |
-        echo "::group::Run clang-tidy"
-        export CC=/usr/bin/clang
-        export CXX=/usr/bin/clang++
+        echo "::group::CMake"
         mkdir build
         cd build
         cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
+        echo "::endgroup::"
+
+        echo "::group::clang-tidy"
         python3 ../utils/run-clang-tidy.py -checks=* > clang-tidy.log
         echo "::endgroup::"
-        ../utils/check_clang_tidy_results.py clang-tidy.log   || true # Let this check fail on errors once we've cleaned up all hits.
+
+        echo "::group::Results"
+        ../utils/check_clang_tidy_results.py clang-tidy.log   || true  # TODO Let this check fail on errors once we've cleaned up all hits.
+        echo "::endgroup::"
 
   linux:
     name: Linux
